In [1]:
import numpy as np

<span style="font-size:20px">Numpy</span>


In [3]:
#Create array
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
temperatures_w1

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [10]:
#Inspect array
print("Shape: ",temperatures_w1.shape)
print("Datatype: ",temperatures_w1.dtype)
print("Size: ",temperatures_w1.size)

Shape:  (7,)
Datatype:  float64
Size:  7


In [12]:
#Array operation
temperatures_w1f = (temperatures_w1 *9/5) + 32
temperatures_w1f

array([72.5 , 77.54, 69.44, 74.12, 78.98, 76.64, 71.42])

In [16]:
print("Maximum: ", np.max(temperatures_w1))
print("Minimum: ", np.min(temperatures_w1))
print("Average: ", np.mean(temperatures_w1).round(2))

Maximum:  26.1
Minimum:  20.8
Average:  23.54


In [19]:
#Array slicing
#First 3 days
temperatures_3 = temperatures_w1[3:]
temperatures_3

array([23.4, 26.1, 24.8, 21.9])

In [22]:
#Weekend
temperatures_end = temperatures_w1[-2:]
temperatures_end

array([24.8, 21.9])

In [23]:
#3 middle days
temperatures_mid = temperatures_w1[2:5]
temperatures_mid

array([20.8, 23.4, 26.1])

In [27]:
#Create 2D Array
temperatures = np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],[19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])
temperatures

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1]])

In [28]:
#Inspect arrray
print("Shape: ",temperatures.shape)
print("Datatype: ",temperatures.dtype)
print("Size: ",temperatures.size)

Shape:  (2, 7)
Datatype:  float64
Size:  14


In [32]:
temp_w1 = temperatures[0]
temp_w2 = temperatures[1]
print("Week 1: ",temp_w1)
print("Week 2: ",temp_w2)

Week 1:  [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2:  [19.2 22.5 21.3 24.  23.5 22.8 20.1]


In [34]:
end1 = temperatures [0,-2:]
end2 = temperatures[1,-2:]
print("Weekend 1: ",end1)
print("Weekend 2: ", end2)

Weekend 1:  [24.8 21.9]
Weekend 2:  [22.8 20.1]


<span style="font-size:20px">Pandas</span>

In [35]:
import pandas as pd

In [40]:
#Create series
marks = pd.Series([95, 92, 89, 85, 80],index = ['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])
marks

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

In [42]:
#Index 
first_rank = marks[0]
first_rank

C:\Users\fathi\AppData\Local\Temp\ipykernel_15452\2887908861.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  first_rank = marks[0]


np.int64(95)

In [43]:
#Using loc
top3= marks.loc[['Rank1','Rank2','Rank3']]
top3

Rank1    95
Rank2    92
Rank3    89
dtype: int64

In [45]:
#Using iloc
rank3 = marks.iloc[2]
rank3

np.int64(89)

In [46]:
#Boolean mask
high_scores = marks[marks>90]
high_scores

Rank1    95
Rank2    92
dtype: int64

In [47]:
#modify first rank
marks[0] = 100
marks

C:\Users\fathi\AppData\Local\Temp\ipykernel_15452\397035428.py:2: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  marks[0] = 100


Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

In [50]:
#Remove fifth rank
marks= marks.drop('Rank5')
marks

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

In [51]:
#Compute CGPA
cgpa = marks / 10
cgpa

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64

In [54]:
#Create dataframe
data = {
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture',
                        'Clothing', 'Electronics', 'Furniture', 'Clothing',
                        'Furniture', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East',
               'West', 'South', 'North'],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
}

transactions = pd.DataFrame(data)
transactions


TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [56]:
transactions.head()


TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

In [60]:
transactions.tail()

TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [63]:
transactions.shape

(10, 4)

In [64]:
transactions.columns

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')

In [61]:
transactions.dtypes

TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object

In [65]:
#Display category and amount
transactions[['ProductCategory','Amount']]

ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

In [69]:
#Last 3 columns
transactions.iloc[:,-3:]

ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

In [72]:
#Filter region and amount
filtered = transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)]
filtered

TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

In [74]:
#Product category value counts
transactions['ProductCategory'].value_counts()

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

In [76]:
#Unique regions
transactions['Region'].unique()

array(['North', 'South', 'East', 'West'], dtype=object)

In [78]:
#Average by region
df = transactions.groupby('Region')['Amount'].mean()
df

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

In [80]:
#Modify amount
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165
transactions

TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [82]:
transactions['Discount'] = transactions['Amount']/ 10
transactions

TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

In [88]:
#Remove row
transactions= transactions.drop(8)
transactions

TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [89]:
#Remove column
transactions = transactions.drop('Discount', axis=1)
transactions

TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400